version: "3"
services:
  web:
    build: .
    depends_on:
      - redis
    ports:
      - "8080:8080"
    environment:
      REDIS_URL: "redis://redis/0"
    volumes:
      - type: bind
        source: ./log
        target: /log

  redis:
    image: redis:latest
    command: ["redis-server", "--appendonly", "yes"]
